apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: influxdb
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/zoklk/GikView.git
    targetRevision: dev
    path: edge/helm/influxdb
    helm:
      releaseName: influxdb
      valueFiles:
        - values.yaml
        - values-prod.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: gikview
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
  ignoreDifferences:
    - group: apps
      kind: StatefulSet
      name: influxdb
      namespace: gikview
      jqPathExpressions:
        - .spec.volumeClaimTemplates
      managedFieldsManagers:
        - kube-controller-manager
