apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mapping-generator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/zoklk/GikView.git
    targetRevision: main
    path: edge/helm/mapping-generator
    helm:
      releaseName: mapping-generator
      valueFiles:
        - values.yaml
        - values-prod.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: gikview
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
