# Operator pre-creates these Secrets off-band (see context/knowledge/step-ca.md):
#   step-ca-certs, step-ca-secrets, step-ca-ca-password, step-ca-admin-jwk,
#   step-issuer-provisioner-password
# And chowns the host PV dir 1000:1000.

step-certificates:
  nodeSelector:
    kubernetes.io/hostname: e-s1
  ca:
    db:
      size: 2Gi

nodePort:
  number: 31900

persistence:
  storageClassName: local-storage
  pvName: step-ca-pv-prod
  hostPath: /mnt/ssd/step-ca
  nodeHostname: e-s1

caJson:
  # yamllint disable-line rule:line-length
  deviceBootstrapRoots: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJuakNDQVVPZ0F3SUJBZ0lRZHhpaVdRamxsYVpib3g4aGk2MTdlekFLQmdncWhrak9QUVFEQWpBYU1SZ3cKRmdZRFZRUURFdzlIYVd0V2FXVjNJRkp2YjNRZ1EwRXdIaGNOTWpZd05URTBNVFl5TURRNFdoY05NekV3TlRFegpNVFl5TURRMVdqQWZNUjB3R3dZRFZRUURFeFJIYVd0V2FXVjNJRUp2YjNSemRISmhjQ0JEUVRCWk1CTUdCeXFHClNNNDlBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJJTFJ1QjlqZnZXZDNnWW9XUXRFT1Z3OXlYU2RSQ2k0YzZObklnaEMKWFdjRCtXTXBUSUR4UXJpTityc01yZng1RCt1czdYR2ZWN25JTHp4ZHpvZUlLb3FqWmpCa01BNEdBMVVkRHdFQgovd1FFQXdJQkJqQVNCZ05WSFJNQkFmOEVDREFHQVFIL0FnRUFNQjBHQTFVZERnUVdCQlNTYjEyUUlVWnZBWnNQCnU2SGg2NlBCTDR5ci96QWZCZ05WSFNNRUdEQVdnQlRHT0JQWllzSE1Uc2xGK3NUbTJkLzU1NkJOWURBS0JnZ3EKaGtqT1BRUURBZ05KQURCR0FpRUEwQ1RXUG41ZmFHT1dUbzU3Nmx6bFlRLzd3OGxBcm5nNXd5RDFzQkg2aE1zQwpJUURpV3h3RXB4TFk2MU5BK1pVd0J5b0MxSTh6QU5QYmVUUndUKytVNFVvdjJ3PT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo="
  # yamllint disable-line rule:line-length
  deviceRenewalRoots: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJuekNDQVVhZ0F3SUJBZ0lRWHpTL3N4dTE2d1U4SDdKdmxmL3gyekFLQmdncWhrak9QUVFEQWpBYU1SZ3cKRmdZRFZRUURFdzlIYVd0V2FXVjNJRkp2YjNRZ1EwRXdIaGNOTWpZd05URTBNVFl4TmpBeFdoY05NekV3TlRFegpNVFl4TlRVeldqQWlNU0F3SGdZRFZRUURFeGRIYVd0V2FXVjNJRWx1ZEdWeWJXVmthV0YwWlNCRFFUQlpNQk1HCkJ5cUdTTTQ5QWdFR0NDcUdTTTQ5QXdFSEEwSUFCSnBwaVlwRXdEdWZ4WUorendRTmdHalk1MHplc0s2UDFuYVMKRFZ5SVRZZjdRSkc3S2huNEE3TjR1cWZyOThzUytjQk4wZndnS3FpNEhuZUYzVW1KSC9lalpqQmtNQTRHQTFVZApEd0VCL3dRRUF3SUJCakFTQmdOVkhSTUJBZjhFQ0RBR0FRSC9BZ0VBTUIwR0ExVWREZ1FXQkJUdGkrS05EM2JjCmwyZlBYdDhMWERKZ2Y4Z2RUREFmQmdOVkhTTUVHREFXZ0JUR09CUFpZc0hNVHNsRitzVG0yZC81NTZCTllEQUsKQmdncWhrak9QUVFEQWdOSEFEQkVBaUF4T0JLV3JpZ2dkbUs3YlBrT1hEN0VSbTJPci9wZ2Z5VkltTCt0U3ZaSAp3d0lnWERNTEFHaytJNzVyYTBBcEJ3WUkydWlQTVo1djRydUo2YUJtMHRTYUhqRT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo="
  adminJwk:
    key:
      use: sig
      kty: EC
      crv: P-256
      alg: ES256
      kid: "KfRD3GwGt3pwdN0DyZI2q-JWt5i_IpgDOnt-D0-lLIE"
      x: "VAueV_FMjCL6Ngxgh61KF9p9at6CGuO5NONSe5EqG80"
      "y": "91LcrOGCovukkuSTbSsQ9Q8E5vGJCHdv0jUw6IKD868"   # quoted: go-yaml parses bare y as bool
    encryptedKey: ""   # loaded from step-ca-admin-jwk Secret at boot
