apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.persistence.pvName }}
  labels:
    {{- include "influxdb.labels" . | nindent 4 }}
spec:
  capacity:
    storage: {{ .Values.persistence.size }}
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Values.persistence.storageClassName }}
  local:
    path: {{ .Values.persistence.hostPath }}
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - {{ .Values.persistence.nodeHostname }}
