apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.datasource.configMapName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "grafana.labels" . | nindent 4 }}
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: {{ .Values.datasource.prometheusUrl | quote }}
        isDefault: true
