apiVersion: cilium.io/v2alpha1
kind: CiliumL2AnnouncementPolicy
metadata:
  name: emqx-l2-policy
  labels:
    {{- include "emqx-lb.labels" . | nindent 4 }}
spec:
  serviceSelector:
    matchLabels:
      app.kubernetes.io/name: emqx-lb
  interfaces:
    {{- range .Values.l2Policy.interfaces }}
    - {{ . | quote }}
    {{- end }}
  externalIPs: false
  loadBalancerIPs: true
