step-issuer:
  nodeSelector:
    kubernetes.io/hostname: e-s1

stepClusterIssuer:
  # yamllint disable-line rule:line-length
  caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJkakNDQVIyZ0F3SUJBZ0lRZlN5TzdmQU1GajlWVExWcG9tcEVrVEFLQmdncWhrak9QUVFEQWpBYU1SZ3cKRmdZRFZRUURFdzlIYVd0V2FXVjNJRkp2YjNRZ1EwRXdIaGNOTWpZd05URTBNVFl4TlRJeVdoY05Nell3TlRFeApNVFl4TlRJeVdqQWFNUmd3RmdZRFZRUURFdzlIYVd0V2FXVjNJRkp2YjNRZ1EwRXdXVEFUQmdjcWhrak9QUUlCCkJnZ3Foa2pPUFFNQkJ3TkNBQVFrWDlmZUJWN0ZZNVNpVXhybS9NcENVazZVY3dVNEU2bm1JZm50ZmpQZk1ZSHAKQTZybFFkczJMU0JXTzlkczJicWZmdEtJeEtVRmN4bWJIOHpxZXl4eW8wVXdRekFPQmdOVkhROEJBZjhFQkFNQwpBUVl3RWdZRFZSMFRBUUgvQkFnd0JnRUIvd0lCQVRBZEJnTlZIUTRFRmdRVXhqZ1QyV0xCekU3SlJmckU1dG5mCitlZWdUV0F3Q2dZSUtvWkl6ajBFQXdJRFJ3QXdSQUlnQmJ5YjEydnF0M292WEFiQzRtRzVlVFBXTTFjelFvREEKTllhS0kramxTUU1DSUgwWXBlWTZ1K29CcHF6MlYyWTFGL1JNQW0rZXVvN2xlYWFEeW9zSUJBVWYKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo="
  kid: "KfRD3GwGt3pwdN0DyZI2q-JWt5i_IpgDOnt-D0-lLIE"
